name: Theme Check

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby-version: ['2.7', '3.0'] # Exemple avec plusieurs versions de Ruby

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install dependencies (Bundler)
      run: |
        gem install bundler
        bundle install

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm install --force
      
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest # Utilisez ubuntu-latest pour simplifier, ajustez selon besoin

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Ajustez à la version de Node.js que vous utilisez
        
    - name: Install dependencies
      run: npm install
      
    - name: Lint
      run: npm run lint
      # Assurez-vous d'avoir configuré un script "lint" dans votre package.json, par exemple avec ESLint pour le JavaScript
      
    - name: Run tests
      run: npm test
      # Ce script doit être configuré dans votre package.json pour exécuter vos tests JavaScript ou tout autre test lié au thème
